version: "3.2"
services:
  api:
    image: node:latest
    container_name: api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - "./server/:/usr/src/app/server"
    working_dir: /usr/src/app/server
    command: bash -c "npm install && 
                      npm run knex:migrate && 
                      npm run knex:seed && 
                      npm start"
  web:
        image: node:latest
        container_name: web
        restart: always
        ports:
          - 3001:3001
        volumes:  
          - "./web/:/usr/src/app/web"
        working_dir: /usr/src/app/web
        command: bash -c "npm install && 
                          npm start"
        network_mode: host